events.listen('item.tags', event =>{
    event.get('forge:ores/diopside').add('blue_skies:everbright_diopside_ore').add('blue_skies:everdawn_diopside_ore')
	event.get('forge:ores/pyrope').add('blue_skies:everbright_pyrope_ore').add('blue_skies:everdawn_pyrope_ore')
	event.get('forge:ores/aquite').add('blue_skies:everbright_aquite_ore').add('blue_skies:everdawn_aquite_ore')
	event.get('forge:ores/charoite').add('blue_skies:everbright_charoite_ore').add('blue_skies:everdawn_charoite_ore')
	event.get('forge:ores/moonstone').add('blue_skies:everbright_moonstone_ore').add('blue_skies:everdawn_moonstone_ore')
	event.get('forge:ores/falsite').add('blue_skies:falsite_ore')
	event.get('forge:ores/ventium').add('blue_skies:ventium_ore')
	event.get('forge:ores/horizonite').add('blue_skies:horizonite_ore')

	event.get('forge:ingots/falsite').add('blue_skies:falsite_ingot')
	event.get('forge:ingots/ventium').add('blue_skies:ventium_ingot')
	event.get('forge:ingots/horizonite').add('blue_skies:horizonite_ingot')

	event.get('forge:gems/diopside').add('blue_skies:diopside_gem')
	event.get('forge:gems/pyrope').add('blue_skies:pyrope_gem')
	event.get('forge:gems/aquite').add('blue_skies:aquite_gem')
	event.get('forge:gems/charoite').add('blue_skies:charoite')
	event.get('forge:gems/moonstone').add('blue_skies:moonstone')

	event.get('forge:storage_blocks/moonstone').add('blue_skies:moonstone_block')
	event.get('forge:storage_blocks/diopside').add('blue_skies:diopside_block')
	event.get('forge:storage_blocks/pyrope').add('blue_skies:pyrope_block')
	event.get('forge:storage_blocks/aquite').add('blue_skies:aquite_block')
	event.get('forge:storage_blocks/charoite').add('blue_skies:charoite_block')
	event.get('forge:storage_blocks/falsite').add('blue_skies:falsite_block')
	event.get('forge:storage_blocks/ventium').add('blue_skies:ventium_block')
	event.get('forge:storage_blocks/horizonite').add('blue_skies:horizonite_block')
})