
#Screen Config
[screen]
	#The duration of GUI background color and blur radius animation in milliseconds. (0 = OFF)
	#Range: 0 ~ 800
	animationDuration = 200
	#Add blur effect to world renderer when opened, it is incompatible with OptiFine's FXAA shader or some mods.
	blurEffect = true
	#The blur effect radius, higher values result in a small loss of performance.
	#Range: 2 ~ 18
	blurRadius = 10
	#A list of GUI screen superclasses that won't activate blur effect when opened.
	blurBlacklist = ["net.minecraft.client.gui.screen.ChatScreen"]
	#The GUI background color in world in 0xAARRGGBB format.
	#Can be one to four values representing top left, top right, bottom right, bottom left color.
	#Multiple values produce a gradient effect, whereas one value has only one color.
	#When values is less than 4, the rest of the corner color will be replaced by the last value.
	backgroundColor = ["0x66000000"]

#Tooltip Config
[tooltip]
	#Enable Modern UI's tooltip style.
	enable = false
	#The tooltip frame color. Format: 0xRRGGBB. Default value: 0xAADCF0
	frameColor = "0x70C3C8"

#General Config
[general]
	#Play a sound effect when the game is loaded.
	ding = true

#Font Config
[font]
	#Allow font renderer to draw text with shadow, setting to false can improve performance a bit.
	allowShadow = true
	#Bitmap-like mode, anti-aliasing and high precision for glyph layouts are OFF.
	#A game restart is required to reload the setting properly.
	bitmapLike = false
	#Fixed resolution level. When the GUI scale increases, the resolution level will not increase.
	#In this case, gui scale should be even numbers (2, 4, 6...), based on Minecraft GUI system.
	#If your fonts are not really bitmap fonts, then you should keep this setting false.
	fixedResolution = false
	#Bilinear sampling font textures with mipmaps, magnification sampling will be always NEAREST.
	#If your fonts are not really bitmap fonts, then you should keep this setting true.
	#A game restart is required to reload the setting properly.
	linearSampling = true
	#A set of font families with precedence relationships to determine the typeface to use.
	#TrueType and OpenTrue are supported. Each list element can be one of the following three cases.
	#1) Font family name for those installed on your PC, for instance: Segoe UI
	#2) File path for external fonts on your PC, for instance: /usr/shared/fonts/x.otf
	#3) Resource location for those loaded with resource packs, for instance: modernui:font/biliw.otf
	#Using pixelated (bitmap) fonts should consider other settings, and glyph size should be 16x.
	#This list is only read once when the game is loaded. A game restart is required to reload
	fontFamily = ["modernui:font/font.ttf", "modernui:font/biliw.otf", "SansSerif"]

