events.listen('recipes', e => {
    e.remove({id: 'bettercompat:smeltery/melting/manasteel_from_block'})
    e.remove({id: 'bettercompat:smeltery/melting/manasteel_from_ingot'})
    e.remove({id: 'bettercompat:smeltery/melting/manasteel_from_nugget'})
    e.remove({id: 'bettercompat:smeltery/melting/elementium_from_block'})
    e.remove({id: 'bettercompat:smeltery/melting/elementium_from_ingot'})
    e.remove({id: 'bettercompat:smeltery/melting/elementium_from_nugget'})
    e.remove({id: 'bettercompat:smeltery/melting/terrasteel_from_block'})
    e.remove({id: 'bettercompat:smeltery/melting/terrasteel_from_ingot'})
    e.remove({id: 'bettercompat:smeltery/melting/terrasteel_from_nugget'})
    e.remove({id: 'bettercompat:smeltery/melting/alfsteel_from_block'})
    e.remove({id: 'bettercompat:smeltery/melting/alfsteel_from_ingot'})
    e.remove({id: 'bettercompat:smeltery/melting/alfsteel_from_nugget'})
})