events.listen('recipes', e => {
    e.custom(
        {
            "type":"botanypots:crop",
            "conditions":[
                {"type":"forge:mod_loaded","modid":"miniutilities"}
            ],
            "seed":{"item":"miniutilities:ender_lily_seeds"},
            "categories":["end_stone"],
            "growthTicks":2000,
            "display":{
                "block":"miniutilities:ender_lily_block",
                "properties":{"age":7}
            },
            "results":[
                {
                    "chance":0.9,
                    "output":{"item":"minecraft:ender_pearl"},
                    "minRolls":1,"maxRolls":1
                },
                {
                    "chance":0.1,
                    "output":{"item":"minecraft:ender_pearl"},
                    "minRolls":1,"maxRolls":1
                },
                {
                    "chance":0.05,
                    "output":{"item":"miniutilities:ender_lily_seeds"},
                    "minRolls":1,"maxRolls":1
                }
            ]
        }
    )

    e.custom(
        {
            "type":"botanypots:crop",
            "conditions":[
                {"type":"forge:mod_loaded","modid":"miniutilities"}
            ],
            "seed":{"item":"miniutilities:flame_lily_seeds"},
            "categories":["sand"],
            "growthTicks":2000,
            "display":{
                "block":"miniutilities:flame_lily_block",
                "properties":{"age":7}
            },
            "results":[
                {
                    "chance":0.9,
                    "output":{"item":"miniutilities:flame_lily"},
                    "minRolls":1,"maxRolls":1
                },
                {
                    "chance":0.1,
                    "output":{"item":"miniutilities:flame_lily"},
                    "minRolls":1,"maxRolls":1
                },
                {
                    "chance":0.05,
                    "output":{"item":"miniutilities:flame_lily_seeds"},
                    "minRolls":1,"maxRolls":1
                }
            ]
        }
    )

    e.custom(
        {
            "type":"botanypots:crop",
            "conditions":[
                {"type":"forge:mod_loaded","modid":"mysticalagriculture"}
            ],
            "seed":{"item":"mysticalagriculture:apatite_seeds"},
            "categories":["prudentium"],
            "growthTicks":2400,
            "display":{
                "block":"mysticalagriculture:apatite_crop",
                "properties":{"age":7}
            },
            "results":[
                {
                    "chance":0.75,
                    "output":{"item":"mysticalagriculture:apatite_essence"},
                    "minRolls":1,"maxRolls":1
                },
                {
                    "chance":0.05,
                    "output":{"item":"mysticalagriculture:apatite_seeds"},
                    "minRolls":1,"maxRolls":1
                },
                {
                    "chance":0.01,
                    "output":{"item":"mysticalagriculture:fertilized_essence"},
                    "minRolls":1,"maxRolls":1
                }
            ]
        }
    )

    e.custom(
        {
            "type":"botanypots:crop",
            "conditions":[
                {"type":"forge:mod_loaded","modid":"mysticalagriculture"}
            ],
            "seed":{"item":"mysticalagriculture:marble_seeds"},
            "categories":["prudentium"],
            "growthTicks":2400,
            "display":{
                "block":"mysticalagriculture:marble_crop",
                "properties":{"age":7}
            },
            "results":[
                {
                    "chance":0.75,
                    "output":{"item":"mysticalagriculture:marble_essence"},
                    "minRolls":1,"maxRolls":1
                },
                {
                    "chance":0.05,
                    "output":{"item":"mysticalagriculture:marble_seeds"},
                    "minRolls":1,"maxRolls":1
                },
                {
                    "chance":0.01,
                    "output":{"item":"mysticalagriculture:fertilized_essence"},
                    "minRolls":1,"maxRolls":1
                }
            ]
        }
    )

    e.custom(
        {
            "type":"botanypots:crop",
            "conditions":[
                {"type":"forge:mod_loaded","modid":"mysticalagriculture"}
            ],
            "seed":{"item":"mysticalagriculture:limestone_seeds"},
            "categories":["prudentium"],
            "growthTicks":2400,
            "display":{
                "block":"mysticalagriculture:limestone_crop",
                "properties":{"age":7}
            },
            "results":[
                {
                    "chance":0.75,
                    "output":{"item":"mysticalagriculture:limestone_essence"},
                    "minRolls":1,"maxRolls":1
                },
                {
                    "chance":0.05,
                    "output":{"item":"mysticalagriculture:limestone_seeds"},
                    "minRolls":1,"maxRolls":1
                },
                {
                    "chance":0.01,
                    "output":{"item":"mysticalagriculture:fertilized_essence"},
                    "minRolls":1,"maxRolls":1
                }
            ]
        }
    )

    e.custom(
        {
            "type":"botanypots:crop",
            "conditions":[
                {"type":"forge:mod_loaded","modid":"mysticalagriculture"}
            ],
            "seed":{"item":"mysticalagriculture:basalt_seeds"},
            "categories":["prudentium"],
            "growthTicks":2400,
            "display":{
                "block":"mysticalagriculture:basalt_crop",
                "properties":{"age":7}
            },
            "results":[
                {
                    "chance":0.75,
                    "output":{"item":"mysticalagriculture:basalt_essence"},
                    "minRolls":1,"maxRolls":1
                },
                {
                    "chance":0.05,
                    "output":{"item":"mysticalagriculture:basalt_seeds"},
                    "minRolls":1,"maxRolls":1
                },
                {
                    "chance":0.01,
                    "output":{"item":"mysticalagriculture:fertilized_essence"},
                    "minRolls":1,"maxRolls":1
                }
            ]
        }
    )

    e.custom(
        {
            "type":"botanypots:crop",
            "conditions":[
                {"type":"forge:mod_loaded","modid":"mysticalagriculture"}
            ],
            "seed":{"item":"mysticalagriculture:tinkers_bronze_seeds"},
            "categories":["prudentium"],
            "growthTicks":3600,
            "display":{
                "block":"mysticalagriculture:tinkers_bronze_crop",
                "properties":{"age":7}
            },
            "results":[
                {
                    "chance":0.75,
                    "output":{"item":"mysticalagriculture:tinkers_bronze_essence"},
                    "minRolls":1,"maxRolls":1
                },
                {
                    "chance":0.05,
                    "output":{"item":"mysticalagriculture:tinkers_bronze_seeds"},
                    "minRolls":1,"maxRolls":1
                },
                {
                    "chance":0.01,
                    "output":{"item":"mysticalagriculture:fertilized_essence"},
                    "minRolls":1,"maxRolls":1
                }
            ]
        }
    )

    e.custom(
        {
            "type":"botanypots:crop",
            "conditions":[
                {"type":"forge:mod_loaded","modid":"mysticalagriculture"}
            ],
            "seed":{"item":"mysticalagriculture:slimesteel_seeds"},
            "categories":["prudentium"],
            "growthTicks":3600,
            "display":{
                "block":"mysticalagriculture:slimesteel_crop",
                "properties":{"age":7}
            },
            "results":[
                {
                    "chance":0.75,
                    "output":{"item":"mysticalagriculture:slimesteel_essence"},
                    "minRolls":1,"maxRolls":1
                },
                {
                    "chance":0.05,
                    "output":{"item":"mysticalagriculture:slimesteel_seeds"},
                    "minRolls":1,"maxRolls":1
                },
                {
                    "chance":0.01,
                    "output":{"item":"mysticalagriculture:fertilized_essence"},
                    "minRolls":1,"maxRolls":1
                }
            ]
        }
    )

    e.custom(
        {
            "type":"botanypots:crop",
            "conditions":[
                {"type":"forge:mod_loaded","modid":"mysticalagriculture"}
            ],
            "seed":{"item":"mysticalagriculture:pig_iron_seeds"},
            "categories":["prudentium"],
            "growthTicks":3600,
            "display":{
                "block":"mysticalagriculture:pig_iron_crop",
                "properties":{"age":7}
            },
            "results":[
                {
                    "chance":0.75,
                    "output":{"item":"mysticalagriculture:pig_iron_essence"},
                    "minRolls":1,"maxRolls":1
                },
                {
                    "chance":0.05,
                    "output":{"item":"mysticalagriculture:pig_iron_seeds"},
                    "minRolls":1,"maxRolls":1
                },
                {
                    "chance":0.01,
                    "output":{"item":"mysticalagriculture:fertilized_essence"},
                    "minRolls":1,"maxRolls":1
                }
            ]
        }
    )

    e.custom(
        {
            "type":"botanypots:crop",
            "conditions":[
                {"type":"forge:mod_loaded","modid":"mysticalagriculture"}
            ],
            "seed":{"item":"mysticalagriculture:steeleaf_seeds"},
            "categories":["prudentium"],
            "growthTicks":3600,
            "display":{
                "block":"mysticalagriculture:steeleaf_crop",
                "properties":{"age":7}
            },
            "results":[
                {
                    "chance":0.75,
                    "output":{"item":"mysticalagriculture:steeleaf_essence"},
                    "minRolls":1,"maxRolls":1
                },
                {
                    "chance":0.05,
                    "output":{"item":"mysticalagriculture:steeleaf_seeds"},
                    "minRolls":1,"maxRolls":1
                },
                {
                    "chance":0.01,
                    "output":{"item":"mysticalagriculture:fertilized_essence"},
                    "minRolls":1,"maxRolls":1
                }
            ]
        }
    )

    e.custom(
        {
            "type":"botanypots:crop",
            "conditions":[
                {"type":"forge:mod_loaded","modid":"mysticalagriculture"}
            ],
            "seed":{"item":"mysticalagriculture:ironwood_seeds"},
            "categories":["prudentium"],
            "growthTicks":3600,
            "display":{
                "block":"mysticalagriculture:ironwood_crop",
                "properties":{"age":7}
            },
            "results":[
                {
                    "chance":0.75,
                    "output":{"item":"mysticalagriculture:ironwood_essence"},
                    "minRolls":1,"maxRolls":1
                },
                {
                    "chance":0.05,
                    "output":{"item":"mysticalagriculture:ironwood_seeds"},
                    "minRolls":1,"maxRolls":1
                },
                {
                    "chance":0.01,
                    "output":{"item":"mysticalagriculture:fertilized_essence"},
                    "minRolls":1,"maxRolls":1
                }
            ]
        }
    )

    e.custom(
        {
            "type":"botanypots:crop",
            "conditions":[
                {"type":"forge:mod_loaded","modid":"mysticalagriculture"}
            ],
            "seed":{"item":"mysticalagriculture:queens_slime_seeds"},
            "categories":["prudentium"],
            "growthTicks":4500,
            "display":{
                "block":"mysticalagriculture:queens_slime_crop",
                "properties":{"age":7}
            },
            "results":[
                {
                    "chance":0.75,
                    "output":{"item":"mysticalagriculture:queens_slime_essence"},
                    "minRolls":1,"maxRolls":1
                },
                {
                    "chance":0.05,
                    "output":{"item":"mysticalagriculture:queens_slime_seeds"},
                    "minRolls":1,"maxRolls":1
                },
                {
                    "chance":0.01,
                    "output":{"item":"mysticalagriculture:fertilized_essence"},
                    "minRolls":1,"maxRolls":1
                }
            ]
        }
    )

    e.custom(
        {
            "type":"botanypots:crop",
            "conditions":[
                {"type":"forge:mod_loaded","modid":"mysticalagriculture"}
            ],
            "seed":{"item":"mysticalagriculture:manyullyn_seeds"},
            "categories":["prudentium"],
            "growthTicks":4500,
            "display":{
                "block":"mysticalagriculture:manyullyn_crop",
                "properties":{"age":7}
            },
            "results":[
                {
                    "chance":0.75,
                    "output":{"item":"mysticalagriculture:manyullyn_essence"},
                    "minRolls":1,"maxRolls":1
                },
                {
                    "chance":0.05,
                    "output":{"item":"mysticalagriculture:manyullyn_seeds"},
                    "minRolls":1,"maxRolls":1
                },
                {
                    "chance":0.01,
                    "output":{"item":"mysticalagriculture:fertilized_essence"},
                    "minRolls":1,"maxRolls":1
                }
            ]
        }
    )

    e.custom(
        {
            "type":"botanypots:crop",
            "conditions":[
                {"type":"forge:mod_loaded","modid":"mysticalagriculture"}
            ],
            "seed":{"item":"mysticalagriculture:fiery_ingot_seeds"},
            "categories":["prudentium"],
            "growthTicks":4000,
            "display":{
                "block":"mysticalagriculture:fiery_ingot_crop",
                "properties":{"age":7}
            },
            "results":[
                {
                    "chance":0.75,
                    "output":{"item":"mysticalagriculture:fiery_ingot_essence"},
                    "minRolls":1,"maxRolls":1
                },
                {
                    "chance":0.05,
                    "output":{"item":"mysticalagriculture:fiery_ingot_seeds"},
                    "minRolls":1,"maxRolls":1
                },
                {
                    "chance":0.01,
                    "output":{"item":"mysticalagriculture:fertilized_essence"},
                    "minRolls":1,"maxRolls":1
                }
            ]
        }
    )

    e.custom(
        {
            "type":"botanypots:crop",
            "conditions":[
                {"type":"forge:mod_loaded","modid":"mysticalagriculture"}
            ],
            "seed":{"item":"mysticalagriculture:knightmetal_seeds"},
            "categories":["prudentium"],
            "growthTicks":4000,
            "display":{
                "block":"mysticalagriculture:knightmetal_crop",
                "properties":{"age":7}
            },
            "results":[
                {
                    "chance":0.75,
                    "output":{"item":"mysticalagriculture:knightmetal_essence"},
                    "minRolls":1,"maxRolls":1
                },
                {
                    "chance":0.05,
                    "output":{"item":"mysticalagriculture:knightmetal_seeds"},
                    "minRolls":1,"maxRolls":1
                },
                {
                    "chance":0.01,
                    "output":{"item":"mysticalagriculture:fertilized_essence"},
                    "minRolls":1,"maxRolls":1
                }
            ]
        }
    )

    e.custom(
        {
            "type":"botanypots:crop",
            "conditions":[
                {"type":"forge:mod_loaded","modid":"mysticalagriculture"}
            ],
            "seed":{"item":"mysticalagriculture:fluorite_seeds"},
            "categories":["prudentium"],
            "growthTicks":4000,
            "display":{
                "block":"mysticalagriculture:fluorite_crop",
                "properties":{"age":7}
            },
            "results":[
                {
                    "chance":0.75,
                    "output":{"item":"mysticalagriculture:fluorite_essence"},
                    "minRolls":1,"maxRolls":1
                },
                {
                    "chance":0.05,
                    "output":{"item":"mysticalagriculture:fluorite_seeds"},
                    "minRolls":1,"maxRolls":1
                },
                {
                    "chance":0.01,
                    "output":{"item":"mysticalagriculture:fertilized_essence"},
                    "minRolls":1,"maxRolls":1
                }
            ]
        }
    )

    e.custom(
        {
            "type":"botanypots:crop",
            "conditions":[
                {"type":"forge:mod_loaded","modid":"mysticalagriculture"}
            ],
            "seed":{"item":"mysticalagriculture:rose_gold_seeds"},
            "categories":["prudentium"],
            "growthTicks":4000,
            "display":{
                "block":"mysticalagriculture:rose_gold_crop",
                "properties":{"age":7}
            },
            "results":[
                {
                    "chance":0.75,
                    "output":{"item":"mysticalagriculture:rose_gold_essence"},
                    "minRolls":1,"maxRolls":1
                },
                {
                    "chance":0.05,
                    "output":{"item":"mysticalagriculture:rose_gold_seeds"},
                    "minRolls":1,"maxRolls":1
                },
                {
                    "chance":0.01,
                    "output":{"item":"mysticalagriculture:fertilized_essence"},
                    "minRolls":1,"maxRolls":1
                }
            ]
        }
    )

    e.custom(
        {
            "type":"botanypots:crop",
            "conditions":[
                {"type":"forge:mod_loaded","modid":"mysticalagriculture"}
            ],
            "seed":{"item":"mysticalagriculture:cobalt_seeds"},
            "categories":["prudentium"],
            "growthTicks":4000,
            "display":{
                "block":"mysticalagriculture:cobalt_crop",
                "properties":{"age":7}
            },
            "results":[
                {
                    "chance":0.75,
                    "output":{"item":"mysticalagriculture:cobalt_essence"},
                    "minRolls":1,"maxRolls":1
                },
                {
                    "chance":0.05,
                    "output":{"item":"mysticalagriculture:cobalt_seeds"},
                    "minRolls":1,"maxRolls":1
                },
                {
                    "chance":0.01,
                    "output":{"item":"mysticalagriculture:fertilized_essence"},
                    "minRolls":1,"maxRolls":1
                }
            ]
        }
    )

    e.custom(
        {
            "type":"botanypots:crop",
            "conditions":[
                {"type":"forge:mod_loaded","modid":"mysticalagriculture"}
            ],
            "seed":{"item":"mysticalagriculture:sapphire_seeds"},
            "categories":["prudentium"],
            "growthTicks":4000,
            "display":{
                "block":"mysticalagriculture:sapphire_crop",
                "properties":{"age":7}
            },
            "results":[
                {
                    "chance":0.75,
                    "output":{"item":"mysticalagriculture:sapphire_essence"},
                    "minRolls":1,"maxRolls":1
                },
                {
                    "chance":0.05,
                    "output":{"item":"mysticalagriculture:sapphire_seeds"},
                    "minRolls":1,"maxRolls":1
                },
                {
                    "chance":0.01,
                    "output":{"item":"mysticalagriculture:fertilized_essence"},
                    "minRolls":1,"maxRolls":1
                }
            ]
        }
    )

    e.custom(
        {
            "type":"botanypots:crop",
            "conditions":[
                {"type":"forge:mod_loaded","modid":"mysticalagriculture"}
            ],
            "seed":{"item":"mysticalagriculture:ruby_seeds"},
            "categories":["prudentium"],
            "growthTicks":4000,
            "display":{
                "block":"mysticalagriculture:ruby_crop",
                "properties":{"age":7}
            },
            "results":[
                {
                    "chance":0.75,
                    "output":{"item":"mysticalagriculture:ruby_essence"},
                    "minRolls":1,"maxRolls":1
                },
                {
                    "chance":0.05,
                    "output":{"item":"mysticalagriculture:ruby_seeds"},
                    "minRolls":1,"maxRolls":1
                },
                {
                    "chance":0.01,
                    "output":{"item":"mysticalagriculture:fertilized_essence"},
                    "minRolls":1,"maxRolls":1
                }
            ]
        }
    )

    e.custom(
        {
            "type":"botanypots:crop",
            "conditions":[
                {"type":"forge:mod_loaded","modid":"mysticalagriculture"}
            ],
            "seed":{"item":"mysticalagriculture:hepatizon_seeds"},
            "categories":["prudentium"],
            "growthTicks":4500,
            "display":{
                "block":"mysticalagriculture:hepatizon_crop",
                "properties":{"age":7}
            },
            "results":[
                {
                    "chance":0.75,
                    "output":{"item":"mysticalagriculture:hepatizon_essence"},
                    "minRolls":1,"maxRolls":1
                },
                {
                    "chance":0.05,
                    "output":{"item":"mysticalagriculture:hepatizon_seeds"},
                    "minRolls":1,"maxRolls":1
                },
                {
                    "chance":0.01,
                    "output":{"item":"mysticalagriculture:fertilized_essence"},
                    "minRolls":1,"maxRolls":1
                }
            ]
        }
    )

    e.custom(
        {
            "type":"botanypots:crop",
            "conditions":[
                {"type":"forge:mod_loaded","modid":"mysticalagriculture"}
            ],
            "seed":{"item":"mysticalagriculture:draconium_seeds"},
            "categories":["prudentium"],
            "growthTicks":4500,
            "display":{
                "block":"mysticalagriculture:draconium_crop",
                "properties":{"age":7}
            },
            "results":[
                {
                    "chance":0.75,
                    "output":{"item":"mysticalagriculture:draconium_essence"},
                    "minRolls":1,"maxRolls":1
                },
                {
                    "chance":0.05,
                    "output":{"item":"mysticalagriculture:draconium_seeds"},
                    "minRolls":1,"maxRolls":1
                },
                {
                    "chance":0.01,
                    "output":{"item":"mysticalagriculture:fertilized_essence"},
                    "minRolls":1,"maxRolls":1
                }
            ]
        }
    )

    e.custom(
        {
            "type":"botanypots:crop",
            "conditions":[
                {"type":"forge:mod_loaded","modid":"mysticalagriculture"}
            ],
            "seed":{"item":"mysticalagriculture:awakened_draconium_seeds"},
            "categories":["prudentium"],
            "growthTicks":4500,
            "display":{
                "block":"mysticalagriculture:awakened_draconium_crop",
                "properties":{"age":7}
            },
            "results":[
                {
                    "chance":0.75,
                    "output":{"item":"mysticalagriculture:awakened_draconium_essence"},
                    "minRolls":1,"maxRolls":1
                },
                {
                    "chance":0.05,
                    "output":{"item":"mysticalagriculture:awakened_draconium_seeds"},
                    "minRolls":1,"maxRolls":1
                },
                {
                    "chance":0.01,
                    "output":{"item":"mysticalagriculture:fertilized_essence"},
                    "minRolls":1,"maxRolls":1
                }
            ]
        }
    )

    e.custom(
        {
            "type":"botanypots:crop",
            "conditions":[
                {"type":"forge:mod_loaded","modid":"mysticalagriculture"}
            ],
            "seed":{"item":"mysticalagriculture:nitro_crystal_seeds"},
            "categories":["prudentium"],
            "growthTicks":4500,
            "display":{
                "block":"mysticalagriculture:nitro_crystal_crop",
                "properties":{"age":7}
            },
            "results":[
                {
                    "chance":0.75,
                    "output":{"item":"mysticalagriculture:nitro_crystal_essence"},
                    "minRolls":1,"maxRolls":1
                },
                {
                    "chance":0.05,
                    "output":{"item":"mysticalagriculture:nitro_crystal_seeds"},
                    "minRolls":1,"maxRolls":1
                },
                {
                    "chance":0.01,
                    "output":{"item":"mysticalagriculture:fertilized_essence"},
                    "minRolls":1,"maxRolls":1
                }
            ]
        }
    )
})