onEvent('recipes', e => {
    e.recipes.custommachinery.custom_machine("custommachinery:fluid_converter", 1)
    .requireFluid(Fluid.of('#forge:experience', 2))
    .produceFluid(Fluid.of('cyclic:xpjuice',2))
    .requireEnergy(1)
    e.recipes.custommachinery.custom_machine("custommachinery:fluid_converter", 1)
    .requireFluid(Fluid.of('cyclic:xpjuice', 2))
    .produceFluid(Fluid.of('industrialforegoing:essence',2))
    .requireEnergy(1)

    e.recipes.custommachinery.custom_machine("custommachinery:fluid_converter", 1)
    .requireFluid(Fluid.of('thermal:ender', 2))
    .produceFluid(Fluid.of('tconstruct:molten_ender',2))
    .requireEnergy(1)
    e.recipes.custommachinery.custom_machine("custommachinery:fluid_converter", 1)
    .requireFluid(Fluid.of('tconstruct:molten_ender', 2))
    .produceFluid(Fluid.of('thermal:ender',2))
    .requireEnergy(1)

    e.recipes.custommachinery.custom_machine("custommachinery:fluid_converter", 1)
    .requireFluid(Fluid.of('industrialforegoing:latex', 2))
    .produceFluid(Fluid.of('thermal:latex',2))
    .requireEnergy(1)
    e.recipes.custommachinery.custom_machine("custommachinery:fluid_converter", 1)
    .requireFluid(Fluid.of('thermal:latex', 2))
    .produceFluid(Fluid.of('industrialforegoing:latex',2))
    .requireEnergy(1)

    e.recipes.custommachinery.custom_machine("custommachinery:fluid_converter", 1)
    .requireFluid(Fluid.of('thermal:creosote', 2))
    .produceFluid(Fluid.of('immersiveengineering:creosote',2))
    .requireEnergy(1)
    e.recipes.custommachinery.custom_machine("custommachinery:fluid_converter", 1)
    .requireFluid(Fluid.of('immersiveengineering:creosote', 2))
    .produceFluid(Fluid.of('thermal:creosote',2))
    .requireEnergy(1)

    e.recipes.custommachinery.custom_machine("custommachinery:fluid_converter", 1)
    .requireFluid(Fluid.of('createadditions:seed_oil', 2))
    .produceFluid(Fluid.of('immersiveengineering:plantoil',2))
    .requireEnergy(1)
    e.recipes.custommachinery.custom_machine("custommachinery:fluid_converter", 1)
    .requireFluid(Fluid.of('immersiveengineering:plantoil', 2))
    .produceFluid(Fluid.of('createadditions:seed_oil',2))
    .requireEnergy(1)

    e.recipes.custommachinery.custom_machine("custommachinery:fluid_converter", 1)
    .requireFluid(Fluid.of('thermal:crude_oil', 2))
    .produceFluid(Fluid.of('immersivepetroleum:oil',2))
    .requireEnergy(1)
    e.recipes.custommachinery.custom_machine("custommachinery:fluid_converter", 1)
    .requireFluid(Fluid.of('immersivepetroleum:oil', 2))
    .produceFluid(Fluid.of('thermal:crude_oil',2))
    .requireEnergy(1)
})