//priority: 99

// ModID abbrs
const mek = 'mekanism:'
const kjs = 'kubejs:'
const ee = 'emendatusenigmatica:'
const ae = 'appliedenergistics2:'
const ec = 'extendedcrafting:'
const rsa = 'redstone_arsenal:'

const disabledItems = [
    rsa + 'flux_helmet',
    rsa + 'flux_chestplate',
    rsa + 'flux_leggings',
    rsa + 'flux_boots',
    rsa + 'flux_elytra',
    rsa + 'flux_controller',
    'boss_tools:blast_furnace',
    'boss_tools_giselle_addon:electric_blast_furnace',
    'projectex:pink_collector',
    'projectex:purple_collector',
    'projectex:violet_collector',
    'projectex:blue_collector',
    'projectex:cyan_collector',
    'projectex:green_collector',
    'projectex:lime_collector',
    'projectex:yellow_collector',
    'projectex:orange_collector',
    'projectex:white_collector',
    'projectex:fading_collector',
    'projectex:final_collector',
    'projectex:pink_relay',
    'projectex:purple_relay',
    'projectex:violet_relay',
    'projectex:blue_relay',
    'projectex:cyan_relay',
    'projectex:green_relay',
    'projectex:lime_relay',
    'projectex:yellow_relay',
    'projectex:orange_relay',
    'projectex:white_relay',
    'projectex:fading_relay',
    'projectex:final_relay',
    'projectex:pink_power_flower',
    'projectex:purple_power_flower',
    'projectex:violet_power_flower',
    'projectex:blue_power_flower',
    'projectex:cyan_power_flower',
    'projectex:green_power_flower',
    'projectex:lime_power_flower',
    'projectex:yellow_power_flower',
    'projectex:orange_power_flower',
    'projectex:white_power_flower',
    'projectex:fading_power_flower',
    'projectex:final_power_flower',
    'extrastorage:storagepart_256k',
    'extrastorage:storagepart_1024k',
    'extrastorage:storagepart_4096k',
    'extrastorage:storagepart_16384k',
    'extrastorage:storagepart_16384k_fluid',
    'extrastorage:storagepart_65536k_fluid',
    'extrastorage:storagepart_262144k_fluid',
    'extrastorage:storagepart_1048576k_fluid',
    'extrastorage:disk_256k',
    'extrastorage:disk_1024k',
    'extrastorage:disk_4096k',
    'extrastorage:disk_16384k',
    'extrastorage:disk_16384k_fluid',
    'extrastorage:disk_65536k_fluid',
    'extrastorage:disk_262144k_fluid',
    'extrastorage:disk_1048576k_fluid',
    'extrastorage:block_256k',
    'extrastorage:block_1024k',
    'extrastorage:block_4096k',
    'extrastorage:block_16384k',
    'extrastorage:block_16384k_fluid',
    'extrastorage:block_65536k_fluid',
    'extrastorage:block_262144k_fluid',
    'extrastorage:block_1048576k_fluid',
]